# Curated Creativity, Art & Science Quotes

CREATIVITY_SCIENCE_QUOTES = [
    # Vincent van Gogh
    {
        "content": "I would rather die of passion than of boredom.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "bold",
        "tags": ["passion", "art", "vitality", "intensity"],
    },
    {
        "content": "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "motivational",
        "tags": ["self-doubt", "action", "creation", "courage"],
    },
    {
        "content": "What is done in love is done well.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "romantic",
        "tags": ["love", "craft", "excellence", "heart"],
    },
    {
        "content": "There is nothing more truly artistic than to love people.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "reflective",
        "tags": ["compassion", "art", "humanity", "love"],
    },
    {
        "content": "Great things are done by a series of small things brought together.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "reflective",
        "tags": ["details", "mastery", "patience", "craftsmanship"],
    },
    {
        "content": "I dream my painting and I paint my dream.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "romantic",
        "tags": ["dreams", "vision", "art", "manifestation"],
    },
    {
        "content": "Normality is a paved road: It's comfortable to walk, but no flowers grow on it.",
        "author": "Vincent van Gogh",
        "category": "Creativity",
        "mood": "philosophical",
        "tags": ["nonconformity", "originality", "beauty", "growth"],
    },

    # Pablo Picasso
    {
        "content": "Every child is an artist. The problem is how to remain an artist once he grows up.",
        "author": "Pablo Picasso",
        "category": "Creativity",
        "mood": "philosophical",
        "tags": ["childhood", "wonder", "art", "imagination"],
    },
    {
        "content": "Action is the foundational key to all success.",
        "author": "Pablo Picasso",
        "category": "Creativity",
        "mood": "bold",
        "tags": ["action", "success", "momentum", "work"],
    },
    {
        "content": "Art washes away from the soul the dust of everyday life.",
        "author": "Pablo Picasso",
        "category": "Creativity",
        "mood": "serene",
        "tags": ["art", "soul", "renewal", "purification"],
    },
    {
        "content": "Everything you can imagine is real.",
        "author": "Pablo Picasso",
        "category": "Creativity",
        "mood": "joyful",
        "tags": ["imagination", "reality", "creation", "belief"],
    },
    {
        "content": "Inspiration exists, but it has to find you working.",
        "author": "Pablo Picasso",
        "category": "Creativity",
        "mood": "motivational",
        "tags": ["inspiration", "discipline", "work-ethic", "craft"],
    },
    {
        "content": "Learn the rules like a pro, so you can break them like an artist.",
        "author": "Pablo Picasso",
        "category": "Creativity",
        "mood": "bold",
        "tags": ["mastery", "innovation", "rules", "rebellion"],
    },

    # Leonardo da Vinci
    {
        "content": "Simplicity is the ultimate sophistication.",
        "author": "Leonardo da Vinci",
        "category": "Creativity",
        "mood": "philosophical",
        "tags": ["simplicity", "design", "elegance", "sophistication"],
    },
    {
        "content": "Learning never exhausts the mind.",
        "author": "Leonardo da Vinci",
        "category": "Creativity",
        "mood": "motivational",
        "tags": ["learning", "curiosity", "intellect", "growth"],
    },
    {
        "content": "Iron rusts from disuse; stagnant water loses its purity; even so does inaction sap the vigor of the mind.",
        "author": "Leonardo da Vinci",
        "category": "Creativity",
        "mood": "bold",
        "tags": ["action", "vigor", "mind", "vitality"],
    },
    {
        "content": "Tears come from the heart and not from the brain.",
        "author": "Leonardo da Vinci",
        "category": "Creativity",
        "mood": "melancholic",
        "tags": ["emotion", "heart", "humanity", "vulnerability"],
    },
    {
        "content": "Art is never finished, only abandoned.",
        "author": "Leonardo da Vinci",
        "category": "Creativity",
        "mood": "philosophical",
        "tags": ["perfectionism", "creation", "craft", "art"],
    },

    # Oscar Wilde & Virginia Woolf & Henri Matisse
    {
        "content": "We are all in the gutter, but some of us are looking at the stars.",
        "author": "Oscar Wilde",
        "category": "Creativity",
        "mood": "romantic",
        "tags": ["hope", "stars", "beauty", "optimism"],
    },
    {
        "content": "You can never be overdressed or overeducated.",
        "author": "Oscar Wilde",
        "category": "Creativity",
        "mood": "joyful",
        "tags": ["style", "education", "wit", "excellence"],
    },
    {
        "content": "The truth is rarely pure and never simple.",
        "author": "Oscar Wilde",
        "category": "Creativity",
        "mood": "philosophical",
        "tags": ["truth", "complexity", "wit", "perspective"],
    },
    {
        "content": "Experience is merely the name men gave to their mistakes.",
        "author": "Oscar Wilde",
        "category": "Creativity",
        "mood": "reflective",
        "tags": ["experience", "mistakes", "learning", "wit"],
    },
    {
        "content": "No need to hurry. No need to sparkle. No need to be anybody but oneself.",
        "author": "Virginia Woolf",
        "category": "Creativity",
        "mood": "serene",
        "tags": ["authenticity", "calm", "individuality", "peace"],
    },
    {
        "content": "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.",
        "author": "Virginia Woolf",
        "category": "Creativity",
        "mood": "bold",
        "tags": ["freedom", "mind", "courage", "intellect"],
    },
    {
        "content": "Arrange whatever pieces come your way.",
        "author": "Virginia Woolf",
        "category": "Creativity",
        "mood": "reflective",
        "tags": ["resourcefulness", "acceptance", "art", "improvisation"],
    },
    {
        "content": "Creativity takes courage.",
        "author": "Henri Matisse",
        "category": "Creativity",
        "mood": "bold",
        "tags": ["courage", "creativity", "expression", "art"],
    },
    {
        "content": "There are always flowers for those who want to see them.",
        "author": "Henri Matisse",
        "category": "Creativity",
        "mood": "joyful",
        "tags": ["perspective", "beauty", "gratitude", "optimism"],
    },

    # Albert Einstein
    {
        "content": "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["imagination", "knowledge", "science", "curiosity"],
    },
    {
        "content": "The important thing is not to stop questioning. Curiosity has its own reason for existence.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "reflective",
        "tags": ["curiosity", "inquiry", "learning", "discovery"],
    },
    {
        "content": "Look deep into nature, and then you will understand everything better.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "serene",
        "tags": ["nature", "understanding", "science", "harmony"],
    },
    {
        "content": "A person who never made a mistake never tried anything new.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "motivational",
        "tags": ["innovation", "mistakes", "experimentation", "risk"],
    },
    {
        "content": "Try not to become a man of success, but rather become a man of value.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "reflective",
        "tags": ["character", "value", "integrity", "purpose"],
    },
    {
        "content": "Life is like riding a bicycle. To keep your balance, you must keep moving.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "motivational",
        "tags": ["balance", "momentum", "life", "movement"],
    },
    {
        "content": "The measure of intelligence is the ability to change.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["intelligence", "adaptability", "evolution", "mind"],
    },
    {
        "content": "Reality is merely an illusion, albeit a very persistent one.",
        "author": "Albert Einstein",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["physics", "reality", "illusion", "perception"],
    },

    # Carl Sagan
    {
        "content": "Somewhere, something incredible is waiting to be known.",
        "author": "Carl Sagan",
        "category": "Science",
        "mood": "serene",
        "tags": ["wonder", "discovery", "cosmos", "curiosity"],
    },
    {
        "content": "For small creatures such as we the vastness is bearable only through love.",
        "author": "Carl Sagan",
        "category": "Science",
        "mood": "romantic",
        "tags": ["love", "cosmos", "humanity", "vastness"],
    },
    {
        "content": "The cosmos is within us. We are made of star-stuff. We are a way for the cosmos to know itself.",
        "author": "Carl Sagan",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["stardust", "universe", "consciousness", "connection"],
    },
    {
        "content": "Extraordinary claims require extraordinary evidence.",
        "author": "Carl Sagan",
        "category": "Science",
        "mood": "bold",
        "tags": ["skepticism", "scientific-method", "evidence", "truth"],
    },
    {
        "content": "Science is not only compatible with spirituality; it is a profound source of spirituality.",
        "author": "Carl Sagan",
        "category": "Science",
        "mood": "reflective",
        "tags": ["spirituality", "science", "reverence", "wonder"],
    },

    # Marie Curie
    {
        "content": "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
        "author": "Marie Curie",
        "category": "Science",
        "mood": "bold",
        "tags": ["understanding", "fearlessness", "knowledge", "science"],
    },
    {
        "content": "Be less curious about people and more curious about ideas.",
        "author": "Marie Curie",
        "category": "Science",
        "mood": "reflective",
        "tags": ["ideas", "intellect", "focus", "curiosity"],
    },
    {
        "content": "One never notices what has been done; one can only see what remains to be done.",
        "author": "Marie Curie",
        "category": "Science",
        "mood": "motivational",
        "tags": ["progress", "discovery", "humility", "focus"],
    },
    {
        "content": "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.",
        "author": "Marie Curie",
        "category": "Science",
        "mood": "bold",
        "tags": ["perseverance", "confidence", "grit", "science"],
    },

    # Richard Feynman
    {
        "content": "I would rather have questions that can't be answered than answers that can't be questioned.",
        "author": "Richard Feynman",
        "category": "Science",
        "mood": "bold",
        "tags": ["curiosity", "inquiry", "humility", "truth"],
    },
    {
        "content": "The first principle is that you must not fool yourself and you are the easiest person to fool.",
        "author": "Richard Feynman",
        "category": "Science",
        "mood": "reflective",
        "tags": ["honesty", "self-awareness", "rigor", "clarity"],
    },
    {
        "content": "Study hard what interests you the most in the most undisciplined, irreverent and original manner possible.",
        "author": "Richard Feynman",
        "category": "Science",
        "mood": "joyful",
        "tags": ["playful-learning", "passion", "originality", "irreverence"],
    },
    {
        "content": "Nature doesn't care what we think.",
        "author": "Richard Feynman",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["reality", "nature", "physics", "truth"],
    },

    # Isaac Newton, Darwin & Stephen Hawking
    {
        "content": "If I have seen further it is by standing on the shoulders of Giants.",
        "author": "Isaac Newton",
        "category": "Science",
        "mood": "reflective",
        "tags": ["humility", "progress", "giants", "discovery"],
    },
    {
        "content": "What we know is a drop, what we don't know is an ocean.",
        "author": "Isaac Newton",
        "category": "Science",
        "mood": "serene",
        "tags": ["mystery", "knowledge", "humility", "ocean"],
    },
    {
        "content": "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.",
        "author": "Isaac Newton",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["simplicity", "truth", "clarity", "nature"],
    },
    {
        "content": "It is not the strongest of the species that survives, nor the most intelligent; it is the one most adaptable to change.",
        "author": "Charles Darwin",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["evolution", "adaptation", "survival", "resilience"],
    },
    {
        "content": "A man who dares to waste one hour of time has not discovered the value of life.",
        "author": "Charles Darwin",
        "category": "Science",
        "mood": "bold",
        "tags": ["time", "value", "purpose", "discipline"],
    },
    {
        "content": "Intelligence is the ability to adapt to change.",
        "author": "Stephen Hawking",
        "category": "Science",
        "mood": "philosophical",
        "tags": ["intelligence", "adaptation", "evolution", "mind"],
    },
    {
        "content": "Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist. Be curious.",
        "author": "Stephen Hawking",
        "category": "Science",
        "mood": "serene",
        "tags": ["stars", "curiosity", "wonder", "universe"],
    },
    {
        "content": "Quiet people have the loudest minds.",
        "author": "Stephen Hawking",
        "category": "Science",
        "mood": "reflective",
        "tags": ["introversion", "intellect", "quietness", "depth"],
    },
]
