# Curated Love, Leadership, Truth & Happiness Quotes

LOVE_LEADERSHIP_QUOTES = [
    # William Shakespeare
    {
        "content": "Love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind.",
        "author": "William Shakespeare",
        "category": "Love",
        "mood": "romantic",
        "tags": ["love", "mind", "perception", "classic"],
    },
    {
        "content": "Doubt thou the stars are fire; Doubt that the sun doth move; Doubt truth to be a liar; But never doubt I love.",
        "author": "William Shakespeare",
        "category": "Love",
        "mood": "romantic",
        "tags": ["devotion", "love", "stars", "truth"],
    },
    {
        "content": "A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.",
        "author": "William Shakespeare",
        "category": "Love",
        "mood": "reflective",
        "tags": ["friendship", "acceptance", "growth", "grace"],
    },
    {
        "content": "Speak low, if you speak love.",
        "author": "William Shakespeare",
        "category": "Love",
        "mood": "serene",
        "tags": ["gentleness", "whisper", "love", "intimacy"],
    },
    {
        "content": "They do not love that do not show their love.",
        "author": "William Shakespeare",
        "category": "Love",
        "mood": "bold",
        "tags": ["action", "expression", "love", "devotion"],
    },

    # Victor Hugo
    {
        "content": "To love or have loved, that is enough. Ask nothing further. There is no other pearl to be found in the dark folds of life.",
        "author": "Victor Hugo",
        "category": "Love",
        "mood": "romantic",
        "tags": ["love", "fulfillment", "heart", "poetry"],
    },
    {
        "content": "Even the darkest night will end and the sun will rise.",
        "author": "Victor Hugo",
        "category": "Truth",
        "mood": "motivational",
        "tags": ["hope", "dawn", "resilience", "faith"],
    },
    {
        "content": "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather loved in spite of ourselves.",
        "author": "Victor Hugo",
        "category": "Love",
        "mood": "romantic",
        "tags": ["acceptance", "unconditional-love", "happiness", "grace"],
    },
    {
        "content": "Music expresses that which cannot be said and on which it is impossible to be silent.",
        "author": "Victor Hugo",
        "category": "Truth",
        "mood": "reflective",
        "tags": ["music", "expression", "soul", "unsayable"],
    },

    # Leo Tolstoy & Jane Austen
    {
        "content": "All, everything that I understand, I understand only because I love.",
        "author": "Leo Tolstoy",
        "category": "Love",
        "mood": "romantic",
        "tags": ["understanding", "love", "illumination", "heart"],
    },
    {
        "content": "True life is lived when tiny changes occur.",
        "author": "Leo Tolstoy",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["tiny-changes", "habits", "living", "growth"],
    },
    {
        "content": "The two most powerful warriors are patience and time.",
        "author": "Leo Tolstoy",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["patience", "time", "strength", "wisdom"],
    },
    {
        "content": "There is no charm equal to tenderness of heart.",
        "author": "Jane Austen",
        "category": "Love",
        "mood": "serene",
        "tags": ["tenderness", "kindness", "gentleness", "heart"],
    },
    {
        "content": "My heart is, and always will be, yours.",
        "author": "Jane Austen",
        "category": "Love",
        "mood": "romantic",
        "tags": ["devotion", "love", "loyalty", "heart"],
    },
    {
        "content": "It isn't what we say or think that defines us, but what we do.",
        "author": "Jane Austen",
        "category": "Truth",
        "mood": "bold",
        "tags": ["action", "character", "integrity", "definition"],
    },

    # Antoine de Saint-Exupéry & Emily Dickinson
    {
        "content": "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
        "author": "Antoine de Saint-Exupéry",
        "category": "Love",
        "mood": "serene",
        "tags": ["heart", "essential", "vision", "invisible"],
    },
    {
        "content": "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
        "author": "Antoine de Saint-Exupéry",
        "category": "Love",
        "mood": "romantic",
        "tags": ["partnership", "unity", "vision", "shared-purpose"],
    },
    {
        "content": "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.",
        "author": "Antoine de Saint-Exupéry",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["simplicity", "minimalism", "perfection", "elegance"],
    },
    {
        "content": "A goal without a plan is just a wish.",
        "author": "Antoine de Saint-Exupéry",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["planning", "goals", "action", "execution"],
    },
    {
        "content": "Hope is the thing with feathers that perches in the soul.",
        "author": "Emily Dickinson",
        "category": "Love",
        "mood": "serene",
        "tags": ["hope", "soul", "feathers", "gentleness"],
    },
    {
        "content": "That it will never come again is what makes life so sweet.",
        "author": "Emily Dickinson",
        "category": "Truth",
        "mood": "melancholic",
        "tags": ["impermanence", "sweetness", "life", "presence"],
    },
    {
        "content": "Forever is composed of nows.",
        "author": "Emily Dickinson",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["now", "eternity", "time", "presence"],
    },

    # Abraham Lincoln
    {
        "content": "Whatever you are, be a good one.",
        "author": "Abraham Lincoln",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["excellence", "authenticity", "integrity", "humility"],
    },
    {
        "content": "Folks are usually about as happy as they make their minds up to be.",
        "author": "Abraham Lincoln",
        "category": "Happiness",
        "mood": "joyful",
        "tags": ["mindset", "happiness", "choice", "perspective"],
    },
    {
        "content": "I am a slow walker, but I never walk back.",
        "author": "Abraham Lincoln",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["persistence", "resolve", "progress", "grit"],
    },
    {
        "content": "Nearly all men can stand adversity, but if you want to test a man's character, give him power.",
        "author": "Abraham Lincoln",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["power", "character", "integrity", "testing"],
    },
    {
        "content": "The best way to predict your future is to create it.",
        "author": "Abraham Lincoln",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["creation", "future", "proactivity", "vision"],
    },

    # Mahatma Gandhi
    {
        "content": "Be the change that you wish to see in the world.",
        "author": "Mahatma Gandhi",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["change", "leadership", "example", "integrity"],
    },
    {
        "content": "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "author": "Mahatma Gandhi",
        "category": "Truth",
        "mood": "motivational",
        "tags": ["learning", "life", "curiosity", "urgency"],
    },
    {
        "content": "The weak can never forgive. Forgiveness is the attribute of the strong.",
        "author": "Mahatma Gandhi",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["forgiveness", "strength", "peace", "grace"],
    },
    {
        "content": "Happiness is when what you think, what you say, and what you do are in harmony.",
        "author": "Mahatma Gandhi",
        "category": "Happiness",
        "mood": "serene",
        "tags": ["harmony", "integrity", "authenticity", "happiness"],
    },
    {
        "content": "Where there is love there is life.",
        "author": "Mahatma Gandhi",
        "category": "Love",
        "mood": "joyful",
        "tags": ["love", "life", "vitality", "spirit"],
    },
    {
        "content": "In a gentle way, you can shake the world.",
        "author": "Mahatma Gandhi",
        "category": "Leadership",
        "mood": "serene",
        "tags": ["gentleness", "impact", "quiet-strength", "leadership"],
    },

    # Eleanor Roosevelt
    {
        "content": "The future belongs to those who believe in the beauty of their dreams.",
        "author": "Eleanor Roosevelt",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["dreams", "future", "belief", "vision"],
    },
    {
        "content": "Do one thing every day that scares you.",
        "author": "Eleanor Roosevelt",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["courage", "comfort-zone", "growth", "bravery"],
    },
    {
        "content": "No one can make you feel inferior without your consent.",
        "author": "Eleanor Roosevelt",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["self-worth", "dignity", "confidence", "boundaries"],
    },
    {
        "content": "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
        "author": "Eleanor Roosevelt",
        "category": "Leadership",
        "mood": "philosophical",
        "tags": ["ideas", "intellect", "elevation", "perspective"],
    },
    {
        "content": "It is better to light a candle than curse the darkness.",
        "author": "Eleanor Roosevelt",
        "category": "Leadership",
        "mood": "reflective",
        "tags": ["hope", "action", "constructive", "light"],
    },

    # Steve Jobs
    {
        "content": "Your time is limited, so don't waste it living someone else's life.",
        "author": "Steve Jobs",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["authenticity", "time", "urgency", "originality"],
    },
    {
        "content": "Stay hungry, stay foolish.",
        "author": "Steve Jobs",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["curiosity", "ambition", "humility", "growth"],
    },
    {
        "content": "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.",
        "author": "Steve Jobs",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["memento-mori", "courage", "risk", "clarity"],
    },
    {
        "content": "Design is not just what it looks like and feels like. Design is how it works.",
        "author": "Steve Jobs",
        "category": "Leadership",
        "mood": "philosophical",
        "tags": ["design", "function", "craft", "excellence"],
    },
    {
        "content": "Have the courage to follow your heart and intuition.",
        "author": "Steve Jobs",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["intuition", "heart", "courage", "calling"],
    },

    # Benjamin Franklin & JFK
    {
        "content": "Tell me and I forget, teach me and I may remember, involve me and I learn.",
        "author": "Benjamin Franklin",
        "category": "Leadership",
        "mood": "reflective",
        "tags": ["learning", "involvement", "education", "wisdom"],
    },
    {
        "content": "An investment in knowledge pays the best interest.",
        "author": "Benjamin Franklin",
        "category": "Leadership",
        "mood": "philosophical",
        "tags": ["knowledge", "growth", "education", "investment"],
    },
    {
        "content": "Energy and persistence conquer all things.",
        "author": "Benjamin Franklin",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["energy", "persistence", "perseverance", "conquest"],
    },
    {
        "content": "Those who dare to fail miserably can achieve greatly.",
        "author": "John F. Kennedy",
        "category": "Leadership",
        "mood": "bold",
        "tags": ["ambition", "failure", "risk", "greatness"],
    },

    # George Orwell & Aleksandr Solzhenitsyn
    {
        "content": "In a time of deceit telling the truth is a revolutionary act.",
        "author": "George Orwell",
        "category": "Truth",
        "mood": "bold",
        "tags": ["truth", "integrity", "courage", "revolution"],
    },
    {
        "content": "Freedom is the right to tell people what they do not want to hear.",
        "author": "George Orwell",
        "category": "Truth",
        "mood": "bold",
        "tags": ["freedom", "free-speech", "honesty", "truth"],
    },
    {
        "content": "Perhaps one did not want to be loved so much as to be understood.",
        "author": "George Orwell",
        "category": "Love",
        "mood": "melancholic",
        "tags": ["understanding", "empathy", "belonging", "humanity"],
    },
    {
        "content": "Live with a steady light inside.",
        "author": "Aleksandr Solzhenitsyn",
        "category": "Truth",
        "mood": "serene",
        "tags": ["inner-light", "steadiness", "integrity", "soul"],
    },
    {
        "content": "The line separating good and evil passes right through every human heart.",
        "author": "Aleksandr Solzhenitsyn",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["morality", "heart", "conscience", "humility"],
    },

    # Carl Jung & James Baldwin
    {
        "content": "Who looks outside, dreams; who looks inside, awakes.",
        "author": "Carl Jung",
        "category": "Truth",
        "mood": "philosophical",
        "tags": ["awakening", "inner-journey", "consciousness", "psyche"],
    },
    {
        "content": "I am not what happened to me, I am what I choose to become.",
        "author": "Carl Jung",
        "category": "Truth",
        "mood": "motivational",
        "tags": ["agency", "self-creation", "choice", "healing"],
    },
    {
        "content": "The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.",
        "author": "Carl Jung",
        "category": "Love",
        "mood": "reflective",
        "tags": ["transformation", "relationships", "alchemy", "connection"],
    },
    {
        "content": "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
        "author": "James Baldwin",
        "category": "Truth",
        "mood": "bold",
        "tags": ["facing-truth", "courage", "change", "honesty"],
    },
    {
        "content": "Love takes off masks that we fear we cannot live without and know we cannot live within.",
        "author": "James Baldwin",
        "category": "Love",
        "mood": "melancholic",
        "tags": ["vulnerability", "authenticity", "masks", "love"],
    },

    # Mark Twain & Audrey Hepburn
    {
        "content": "The secret of getting ahead is getting started.",
        "author": "Mark Twain",
        "category": "Leadership",
        "mood": "motivational",
        "tags": ["starting", "action", "initiative", "momentum"],
    },
    {
        "content": "Kindness is the language which the deaf can hear and the blind can see.",
        "author": "Mark Twain",
        "category": "Love",
        "mood": "serene",
        "tags": ["kindness", "universal", "compassion", "humanity"],
    },
    {
        "content": "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
        "author": "Mark Twain",
        "category": "Happiness",
        "mood": "motivational",
        "tags": ["regret", "daring", "adventure", "life"],
    },
    {
        "content": "Give every day the chance to become the most beautiful day of your life.",
        "author": "Mark Twain",
        "category": "Happiness",
        "mood": "joyful",
        "tags": ["beauty", "hope", "today", "happiness"],
    },
    {
        "content": "Nothing is impossible, the word itself says 'I'm possible'!",
        "author": "Audrey Hepburn",
        "category": "Happiness",
        "mood": "joyful",
        "tags": ["possibility", "optimism", "joy", "hope"],
    },
    {
        "content": "The most important thing is to enjoy your life - to be happy - it's all that matters.",
        "author": "Audrey Hepburn",
        "category": "Happiness",
        "mood": "joyful",
        "tags": ["happiness", "enjoyment", "simplicity", "life"],
    },
    {
        "content": "To plant a garden is to believe in tomorrow.",
        "author": "Audrey Hepburn",
        "category": "Happiness",
        "mood": "serene",
        "tags": ["garden", "tomorrow", "faith", "hope"],
    },
]
