# Curated Resilience & Courage Quotes

RESILIENCE_COURAGE_QUOTES = [
    # Viktor Frankl
    {
        "content": "When we are no longer able to change a situation, we are challenged to change ourselves.",
        "author": "Viktor Frankl",
        "category": "Resilience",
        "mood": "philosophical",
        "tags": ["adaptation", "inner-change", "growth", "meaning"],
    },
    {
        "content": "Everything can be taken from a man but one thing: the last of the human freedoms - to choose one's attitude in any given set of circumstances.",
        "author": "Viktor Frankl",
        "category": "Resilience",
        "mood": "bold",
        "tags": ["freedom", "attitude", "resilience", "human-spirit"],
    },
    {
        "content": "Those who have a 'why' to live, can bear with almost any 'how'.",
        "author": "Viktor Frankl",
        "category": "Resilience",
        "mood": "philosophical",
        "tags": ["purpose", "perseverance", "endurance", "meaning"],
    },
    {
        "content": "Between stimulus and response there is a space. In that space is our power to choose our response.",
        "author": "Viktor Frankl",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["choice", "mindset", "self-control", "awareness"],
    },
    {
        "content": "What is to give light must endure burning.",
        "author": "Viktor Frankl",
        "category": "Resilience",
        "mood": "melancholic",
        "tags": ["sacrifice", "endurance", "light", "purpose"],
    },

    # Nelson Mandela
    {
        "content": "It always seems impossible until it's done.",
        "author": "Nelson Mandela",
        "category": "Courage",
        "mood": "motivational",
        "tags": ["perseverance", "hope", "achievement", "leadership"],
    },
    {
        "content": "The greatest glory in living lies not in never falling, but in rising every time we fall.",
        "author": "Nelson Mandela",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["rising", "resilience", "endurance", "spirit"],
    },
    {
        "content": "I never lose. I either win or learn.",
        "author": "Nelson Mandela",
        "category": "Courage",
        "mood": "bold",
        "tags": ["learning", "mindset", "victory", "growth"],
    },
    {
        "content": "Resentment is like drinking poison and then hoping it will kill your enemies.",
        "author": "Nelson Mandela",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["forgiveness", "healing", "peace", "wisdom"],
    },
    {
        "content": "A winner is a dreamer who never gives up.",
        "author": "Nelson Mandela",
        "category": "Courage",
        "mood": "motivational",
        "tags": ["dreams", "determination", "grit", "success"],
    },
    {
        "content": "May your choices reflect your hopes, not your fears.",
        "author": "Nelson Mandela",
        "category": "Courage",
        "mood": "reflective",
        "tags": ["hope", "choices", "courage", "overcoming-fear"],
    },
    {
        "content": "Courage was not the absence of fear, but the triumph over it.",
        "author": "Nelson Mandela",
        "category": "Courage",
        "mood": "bold",
        "tags": ["courage", "bravery", "conquest", "triumph"],
    },

    # Winston Churchill
    {
        "content": "If you're going through hell, keep going.",
        "author": "Winston Churchill",
        "category": "Resilience",
        "mood": "bold",
        "tags": ["endurance", "perseverance", "grit", "strength"],
    },
    {
        "content": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
        "author": "Winston Churchill",
        "category": "Courage",
        "mood": "bold",
        "tags": ["perseverance", "courage", "failure", "success"],
    },
    {
        "content": "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
        "author": "Winston Churchill",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["optimism", "perspective", "mindset", "opportunity"],
    },
    {
        "content": "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
        "author": "Winston Churchill",
        "category": "Courage",
        "mood": "philosophical",
        "tags": ["courage", "humility", "listening", "speaking"],
    },
    {
        "content": "Never, never, never give up.",
        "author": "Winston Churchill",
        "category": "Resilience",
        "mood": "bold",
        "tags": ["grit", "determination", "tenacity", "strength"],
    },
    {
        "content": "Attitude is a little thing that makes a big difference.",
        "author": "Winston Churchill",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["attitude", "perspective", "mindset", "impact"],
    },

    # Theodore Roosevelt
    {
        "content": "It is not the critic who counts; not the man who points out how the strong man stumbles. The credit belongs to the man who is actually in the arena.",
        "author": "Theodore Roosevelt",
        "category": "Courage",
        "mood": "bold",
        "tags": ["courage", "arena", "action", "vulnerability"],
    },
    {
        "content": "Do what you can, with what you have, where you are.",
        "author": "Theodore Roosevelt",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["action", "resourcefulness", "pragmatism", "grit"],
    },
    {
        "content": "Believe you can and you're halfway there.",
        "author": "Theodore Roosevelt",
        "category": "Courage",
        "mood": "motivational",
        "tags": ["belief", "confidence", "mindset", "success"],
    },
    {
        "content": "Far and away the best prize that life has to offer is the chance to work hard at work worth doing.",
        "author": "Theodore Roosevelt",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["purpose", "work", "dedication", "fulfillment"],
    },
    {
        "content": "Courage is not having the strength to go on; it is going on when you don't have the strength.",
        "author": "Theodore Roosevelt",
        "category": "Courage",
        "mood": "melancholic",
        "tags": ["courage", "endurance", "fortitude", "heart"],
    },

    # Helen Keller
    {
        "content": "Although the world is full of suffering, it is also full of the overcoming of it.",
        "author": "Helen Keller",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["overcoming", "hope", "strength", "resilience"],
    },
    {
        "content": "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.",
        "author": "Helen Keller",
        "category": "Resilience",
        "mood": "philosophical",
        "tags": ["character", "adversity", "soul", "growth"],
    },
    {
        "content": "Security is mostly a superstition. Life is either a daring adventure or nothing.",
        "author": "Helen Keller",
        "category": "Courage",
        "mood": "bold",
        "tags": ["adventure", "daring", "courage", "risk"],
    },
    {
        "content": "Keep your face to the sunshine and you cannot see a shadow.",
        "author": "Helen Keller",
        "category": "Resilience",
        "mood": "serene",
        "tags": ["sunshine", "positivity", "light", "focus"],
    },
    {
        "content": "Alone we can do so little; together we can do so much.",
        "author": "Helen Keller",
        "category": "Courage",
        "mood": "reflective",
        "tags": ["unity", "community", "collaboration", "together"],
    },

    # Ernest Hemingway
    {
        "content": "The world breaks everyone and afterward many are strong at the broken places.",
        "author": "Ernest Hemingway",
        "category": "Resilience",
        "mood": "melancholic",
        "tags": ["kintsugi", "healing", "brokenness", "resilience"],
    },
    {
        "content": "Courage is grace under pressure.",
        "author": "Ernest Hemingway",
        "category": "Courage",
        "mood": "bold",
        "tags": ["grace", "poise", "courage", "pressure"],
    },
    {
        "content": "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.",
        "author": "Ernest Hemingway",
        "category": "Courage",
        "mood": "philosophical",
        "tags": ["self-improvement", "nobility", "humility", "growth"],
    },
    {
        "content": "Man is not made for defeat. A man can be destroyed but not defeated.",
        "author": "Ernest Hemingway",
        "category": "Resilience",
        "mood": "bold",
        "tags": ["indomitable", "spirit", "victory", "endurance"],
    },

    # Maya Angelou
    {
        "content": "You may not control all the events that happen to you, but you can decide not to be reduced by them.",
        "author": "Maya Angelou",
        "category": "Resilience",
        "mood": "bold",
        "tags": ["resilience", "dignity", "power", "control"],
    },
    {
        "content": "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.",
        "author": "Maya Angelou",
        "category": "Courage",
        "mood": "bold",
        "tags": ["virtue", "courage", "consistency", "integrity"],
    },
    {
        "content": "If you don't like something, change it. If you can't change it, change your attitude.",
        "author": "Maya Angelou",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["attitude", "acceptance", "agency", "perspective"],
    },
    {
        "content": "Nothing can dim the light which shines from within.",
        "author": "Maya Angelou",
        "category": "Courage",
        "mood": "serene",
        "tags": ["inner-light", "strength", "radiance", "hope"],
    },
    {
        "content": "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.",
        "author": "Maya Angelou",
        "category": "Courage",
        "mood": "joyful",
        "tags": ["thriving", "passion", "style", "life"],
    },

    # Martin Luther King Jr.
    {
        "content": "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
        "author": "Martin Luther King Jr.",
        "category": "Courage",
        "mood": "bold",
        "tags": ["love", "light", "justice", "nonviolence"],
    },
    {
        "content": "The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge and controversy.",
        "author": "Martin Luther King Jr.",
        "category": "Courage",
        "mood": "bold",
        "tags": ["character", "conviction", "integrity", "adversity"],
    },
    {
        "content": "Faith is taking the first step even when you don't see the whole staircase.",
        "author": "Martin Luther King Jr.",
        "category": "Courage",
        "mood": "serene",
        "tags": ["faith", "trust", "courage", "step"],
    },
    {
        "content": "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
        "author": "Martin Luther King Jr.",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["perseverance", "progress", "momentum", "grit"],
    },
    {
        "content": "Our lives begin to end the day we become silent about things that matter.",
        "author": "Martin Luther King Jr.",
        "category": "Courage",
        "mood": "bold",
        "tags": ["voice", "justice", "courage", "truth"],
    },
    {
        "content": "Injustice anywhere is a threat to justice everywhere.",
        "author": "Martin Luther King Jr.",
        "category": "Courage",
        "mood": "bold",
        "tags": ["justice", "interconnectedness", "equality", "solidarity"],
    },

    # Rosa Parks, Amelia Earhart & Muhammad Ali
    {
        "content": "I have learned over the years that when one's mind is made up, this diminishes fear.",
        "author": "Rosa Parks",
        "category": "Courage",
        "mood": "reflective",
        "tags": ["resolution", "fearlessness", "conviction", "courage"],
    },
    {
        "content": "Stand for something or you will fall for anything. Today's mighty oak is yesterday's nut that held its ground.",
        "author": "Rosa Parks",
        "category": "Courage",
        "mood": "bold",
        "tags": ["conviction", "roots", "tenacity", "strength"],
    },
    {
        "content": "The most difficult thing is the decision to act, the rest is merely tenacity.",
        "author": "Amelia Earhart",
        "category": "Courage",
        "mood": "motivational",
        "tags": ["action", "tenacity", "decision", "courage"],
    },
    {
        "content": "Courage is the price that life exacts for granting peace.",
        "author": "Amelia Earhart",
        "category": "Courage",
        "mood": "philosophical",
        "tags": ["courage", "peace", "freedom", "conviction"],
    },
    {
        "content": "Don't count the days, make the days count.",
        "author": "Muhammad Ali",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["urgency", "purpose", "dedication", "discipline"],
    },
    {
        "content": "He who is not courageous enough to take risks will accomplish nothing in life.",
        "author": "Muhammad Ali",
        "category": "Courage",
        "mood": "bold",
        "tags": ["risk", "courage", "achievement", "daring"],
    },
    {
        "content": "Impossible is not a declaration. It's a dare. Impossible is potential. Impossible is temporary. Impossible is nothing.",
        "author": "Muhammad Ali",
        "category": "Courage",
        "mood": "bold",
        "tags": ["defiance", "potential", "greatness", "belief"],
    },

    # C.S. Lewis & Booker T. Washington
    {
        "content": "Courage is not simply one of the virtues, but the form of every virtue at the testing point.",
        "author": "C.S. Lewis",
        "category": "Courage",
        "mood": "philosophical",
        "tags": ["virtue", "testing", "strength", "character"],
    },
    {
        "content": "Hardships often prepare ordinary people for an extraordinary destiny.",
        "author": "C.S. Lewis",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["hardship", "destiny", "transformation", "hope"],
    },
    {
        "content": "You can't go back and change the beginning, but you can start where you are and change the ending.",
        "author": "C.S. Lewis",
        "category": "Resilience",
        "mood": "motivational",
        "tags": ["starting-over", "renewal", "hope", "action"],
    },
    {
        "content": "I have learned that success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.",
        "author": "Booker T. Washington",
        "category": "Resilience",
        "mood": "reflective",
        "tags": ["success", "obstacles", "perseverance", "character"],
    },
    {
        "content": "Character, not circumstance, makes the person.",
        "author": "Booker T. Washington",
        "category": "Resilience",
        "mood": "philosophical",
        "tags": ["character", "integrity", "strength", "resilience"],
    },
]
