# Curated Nature & Mindfulness Quotes

NATURE_MINDFULNESS_QUOTES = [
    # Henry David Thoreau
    {
        "content": "I went to the woods because I wished to live deliberately, to front only the essential facts of life.",
        "author": "Henry David Thoreau",
        "category": "Nature",
        "mood": "reflective",
        "tags": ["deliberate-living", "woods", "simplicity", "solitude"],
    },
    {
        "content": "Not until we are lost do we begin to understand ourselves.",
        "author": "Henry David Thoreau",
        "category": "Nature",
        "mood": "philosophical",
        "tags": ["self-discovery", "wilderness", "understanding", "growth"],
    },
    {
        "content": "Go confidently in the direction of your dreams! Live the life you've imagined.",
        "author": "Henry David Thoreau",
        "category": "Mindfulness",
        "mood": "motivational",
        "tags": ["dreams", "confidence", "purpose", "authenticity"],
    },
    {
        "content": "Rather than love, than money, than fame, give me truth.",
        "author": "Henry David Thoreau",
        "category": "Mindfulness",
        "mood": "bold",
        "tags": ["truth", "integrity", "simplicity", "values"],
    },
    {
        "content": "The cost of a thing is the amount of what I will call life which is required to be exchanged for it.",
        "author": "Henry David Thoreau",
        "category": "Mindfulness",
        "mood": "philosophical",
        "tags": ["time", "values", "life", "simplicity"],
    },
    {
        "content": "Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influence of the earth.",
        "author": "Henry David Thoreau",
        "category": "Nature",
        "mood": "serene",
        "tags": ["seasons", "earth", "presence", "nature"],
    },
    {
        "content": "This world is but a canvas to our imagination.",
        "author": "Henry David Thoreau",
        "category": "Nature",
        "mood": "serene",
        "tags": ["imagination", "nature", "canvas", "creativity"],
    },
    {
        "content": "In wildness is the preservation of the world.",
        "author": "Henry David Thoreau",
        "category": "Nature",
        "mood": "bold",
        "tags": ["wildness", "conservation", "nature", "spirit"],
    },

    # Ralph Waldo Emerson
    {
        "content": "Do not go where the path may lead, go instead where there is no path and leave a trail.",
        "author": "Ralph Waldo Emerson",
        "category": "Nature",
        "mood": "bold",
        "tags": ["pioneering", "trailblazing", "authenticity", "courage"],
    },
    {
        "content": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
        "author": "Ralph Waldo Emerson",
        "category": "Mindfulness",
        "mood": "bold",
        "tags": ["authenticity", "self-reliance", "individuality", "courage"],
    },
    {
        "content": "The only person you are destined to become is the person you decide to be.",
        "author": "Ralph Waldo Emerson",
        "category": "Mindfulness",
        "mood": "motivational",
        "tags": ["destiny", "self-determination", "choice", "growth"],
    },
    {
        "content": "Adopt the pace of nature: her secret is patience.",
        "author": "Ralph Waldo Emerson",
        "category": "Nature",
        "mood": "serene",
        "tags": ["patience", "nature", "rhythm", "calm"],
    },
    {
        "content": "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
        "author": "Ralph Waldo Emerson",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["inner-strength", "potential", "spirit", "soul"],
    },
    {
        "content": "For every minute you are angry you lose sixty seconds of happiness.",
        "author": "Ralph Waldo Emerson",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["anger", "happiness", "peace", "time"],
    },
    {
        "content": "Write it on your heart that every day is the best day in the year.",
        "author": "Ralph Waldo Emerson",
        "category": "Mindfulness",
        "mood": "joyful",
        "tags": ["gratitude", "optimism", "today", "presence"],
    },

    # John Muir
    {
        "content": "The mountains are calling and I must go.",
        "author": "John Muir",
        "category": "Nature",
        "mood": "serene",
        "tags": ["mountains", "nature", "wanderlust", "wilderness"],
    },
    {
        "content": "In every walk with nature one receives far more than he seeks.",
        "author": "John Muir",
        "category": "Nature",
        "mood": "serene",
        "tags": ["nature", "serenity", "discovery", "peace"],
    },
    {
        "content": "The clearest way into the Universe is through a forest wilderness.",
        "author": "John Muir",
        "category": "Nature",
        "mood": "reflective",
        "tags": ["forest", "universe", "spirit", "wilderness"],
    },
    {
        "content": "Keep close to Nature's heart... and break clear away, once in awhile, and climb a mountain or spend a week in the woods. Wash your spirit clean.",
        "author": "John Muir",
        "category": "Nature",
        "mood": "serene",
        "tags": ["renewal", "woods", "spirit", "solitude"],
    },
    {
        "content": "Between every two pines there is a door to a new world.",
        "author": "John Muir",
        "category": "Nature",
        "mood": "serene",
        "tags": ["pines", "wonder", "nature", "doors"],
    },
    {
        "content": "Going to the mountains is going home.",
        "author": "John Muir",
        "category": "Nature",
        "mood": "reflective",
        "tags": ["mountains", "home", "belonging", "peace"],
    },

    # Mary Oliver & Walt Whitman
    {
        "content": "Tell me, what is it you plan to do with your one wild and precious life?",
        "author": "Mary Oliver",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["purpose", "presence", "life", "wonder"],
    },
    {
        "content": "Instructions for living a life: Pay attention. Be astonished. Tell about it.",
        "author": "Mary Oliver",
        "category": "Mindfulness",
        "mood": "joyful",
        "tags": ["attention", "astonishment", "wonder", "art"],
    },
    {
        "content": "Keep some room in your heart for the unimaginable.",
        "author": "Mary Oliver",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["wonder", "mystery", "hope", "heart"],
    },
    {
        "content": "You do not have to be good. You only have to let the soft animal of your body love what it loves.",
        "author": "Mary Oliver",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["acceptance", "self-love", "nature", "gentleness"],
    },
    {
        "content": "Keep your face always toward the sunshine - and shadows will fall behind you.",
        "author": "Walt Whitman",
        "category": "Nature",
        "mood": "joyful",
        "tags": ["sunshine", "light", "optimism", "shadows"],
    },
    {
        "content": "I am large, I contain multitudes.",
        "author": "Walt Whitman",
        "category": "Mindfulness",
        "mood": "bold",
        "tags": ["identity", "complexity", "humanity", "acceptance"],
    },
    {
        "content": "Re-examine all you have been told. Dismiss whatever insults your own soul.",
        "author": "Walt Whitman",
        "category": "Mindfulness",
        "mood": "bold",
        "tags": ["authenticity", "soul", "discernment", "truth"],
    },
    {
        "content": "Now I see the secret of making the best person: it is to grow in the open air and to eat and sleep with the earth.",
        "author": "Walt Whitman",
        "category": "Nature",
        "mood": "serene",
        "tags": ["nature", "earth", "growth", "simplicity"],
    },

    # Matsuo Basho & Japanese Sages
    {
        "content": "Do not seek to follow in the footsteps of the wise; seek what they sought.",
        "author": "Matsuo Basho",
        "category": "Nature",
        "mood": "philosophical",
        "tags": ["wisdom", "originality", "seeking", "authenticity"],
    },
    {
        "content": "Every day is a journey, and the journey itself is home.",
        "author": "Matsuo Basho",
        "category": "Nature",
        "mood": "serene",
        "tags": ["journey", "home", "presence", "zen"],
    },
    {
        "content": "Sitting quietly, doing nothing, spring comes, and the grass grows by itself.",
        "author": "Matsuo Basho",
        "category": "Nature",
        "mood": "serene",
        "tags": ["stillness", "non-doing", "nature", "zen"],
    },

    # Gautama Buddha
    {
        "content": "Peace comes from within. Do not seek it without.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["peace", "inner-calm", "meditation", "stillness"],
    },
    {
        "content": "The mind is everything. What you think you become.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["mind", "thoughts", "transformation", "awareness"],
    },
    {
        "content": "Three things cannot be long hidden: the sun, the moon, and the truth.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "philosophical",
        "tags": ["truth", "light", "clarity", "inevitability"],
    },
    {
        "content": "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["contentment", "health", "wealth", "gratitude"],
    },
    {
        "content": "You only lose what you cling to.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["non-attachment", "letting-go", "freedom", "zen"],
    },
    {
        "content": "Radiate boundless love towards the entire world.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "romantic",
        "tags": ["metta", "compassion", "love", "unity"],
    },
    {
        "content": "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you.",
        "author": "Gautama Buddha",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["love", "gentleness", "letting-go", "grace"],
    },

    # Eckhart Tolle
    {
        "content": "Realize deeply that the present moment is all you have. Make the NOW the primary focus of your life.",
        "author": "Eckhart Tolle",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["now", "presence", "awareness", "stillness"],
    },
    {
        "content": "Whatever the present moment contains, accept it as if you had chosen it.",
        "author": "Eckhart Tolle",
        "category": "Mindfulness",
        "mood": "philosophical",
        "tags": ["acceptance", "surrender", "presence", "peace"],
    },
    {
        "content": "Life will give you whatever experience is most helpful for the evolution of your consciousness.",
        "author": "Eckhart Tolle",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["consciousness", "evolution", "growth", "lessons"],
    },
    {
        "content": "Worry pretends to be necessary but serves no useful purpose.",
        "author": "Eckhart Tolle",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["worry", "peace", "clarity", "freedom"],
    },
    {
        "content": "Acknowledging the good that you already have in your life is the foundation for all abundance.",
        "author": "Eckhart Tolle",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["abundance", "gratitude", "contentment", "wealth"],
    },
    {
        "content": "To love is to recognize yourself in another.",
        "author": "Eckhart Tolle",
        "category": "Mindfulness",
        "mood": "romantic",
        "tags": ["oneness", "love", "compassion", "empathy"],
    },

    # Thich Nhat Hanh
    {
        "content": "Smile, breathe and go slowly.",
        "author": "Thich Nhat Hanh",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["breathing", "slowness", "smile", "peace"],
    },
    {
        "content": "Present moment wonderful moment.",
        "author": "Thich Nhat Hanh",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["now", "wonder", "gratitude", "mindfulness"],
    },
    {
        "content": "Because you are alive, everything is possible.",
        "author": "Thich Nhat Hanh",
        "category": "Mindfulness",
        "mood": "joyful",
        "tags": ["life", "hope", "possibility", "vitality"],
    },
    {
        "content": "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.",
        "author": "Thich Nhat Hanh",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["emotions", "breath", "anchor", "stability"],
    },
    {
        "content": "There is no way to peace - peace is the way.",
        "author": "Thich Nhat Hanh",
        "category": "Mindfulness",
        "mood": "philosophical",
        "tags": ["peace", "living", "nonviolence", "simplicity"],
    },
    {
        "content": "Walk as if you are kissing the Earth with your feet.",
        "author": "Thich Nhat Hanh",
        "category": "Nature",
        "mood": "serene",
        "tags": ["earth", "reverence", "walking-meditation", "care"],
    },

    # Hermann Hesse
    {
        "content": "Some of us think holding on makes us strong, but sometimes it is letting go.",
        "author": "Hermann Hesse",
        "category": "Mindfulness",
        "mood": "reflective",
        "tags": ["letting-go", "strength", "surrender", "wisdom"],
    },
    {
        "content": "Within you there is a stillness and a sanctuary to which you can retreat at any time.",
        "author": "Hermann Hesse",
        "category": "Mindfulness",
        "mood": "serene",
        "tags": ["sanctuary", "inner-stillness", "refuge", "peace"],
    },
    {
        "content": "I have been and still am a seeker, but I have ceased to question stars and books; I have begun to listen to the teaching my blood whispers to me.",
        "author": "Hermann Hesse",
        "category": "Mindfulness",
        "mood": "philosophical",
        "tags": ["seeker", "intuition", "self-trust", "listening"],
    },
]
