# Curated Wisdom & Mysticism Quotes (Taoism, Sufism, Zen, Ancient Sages)

WISDOM_QUOTES = [
    # Lao Tzu
    {
        "content": "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["self-mastery", "wisdom", "taoism", "power"],
    },
    {
        "content": "When you are content to be simply yourself and don't compare or compete, everyone will respect you.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["contentment", "authenticity", "respect", "taoism"],
    },
    {
        "content": "Silence is a source of great strength.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["silence", "inner-peace", "strength", "stillness"],
    },
    {
        "content": "Simplicity, patience, compassion. These three are your greatest treasures.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["simplicity", "patience", "compassion", "virtue"],
    },
    {
        "content": "A good traveler has no fixed plans, and is not intent on arriving.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "reflective",
        "tags": ["journey", "flow", "travel", "taoism"],
    },
    {
        "content": "Do you have the patience to wait until your mud settles and the water is clear?",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "reflective",
        "tags": ["patience", "clarity", "mindfulness", "stillness"],
    },
    {
        "content": "He who knows that enough is enough will always have enough.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["contentment", "abundance", "gratitude", "taoism"],
    },
    {
        "content": "Act without expectation.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["detachment", "action", "peace", "taoism"],
    },
    {
        "content": "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "romantic",
        "tags": ["kindness", "love", "generosity", "grace"],
    },
    {
        "content": "Care about what other people think and you will always be their prisoner.",
        "author": "Lao Tzu",
        "category": "Wisdom",
        "mood": "bold",
        "tags": ["freedom", "independence", "opinions", "confidence"],
    },

    # Confucius
    {
        "content": "It does not matter how slowly you go as long as you do not stop.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "motivational",
        "tags": ["persistence", "perseverance", "progress", "patience"],
    },
    {
        "content": "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["wisdom", "reflection", "experience", "learning"],
    },
    {
        "content": "The man who moves a mountain begins by carrying away small stones.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "motivational",
        "tags": ["discipline", "action", "habits", "goals"],
    },
    {
        "content": "Everything has beauty, but not everyone sees it.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["beauty", "perception", "mindfulness", "gratitude"],
    },
    {
        "content": "Real knowledge is to know the extent of one's ignorance.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "reflective",
        "tags": ["humility", "knowledge", "learning", "wisdom"],
    },
    {
        "content": "He who conquers himself is the mightiest warrior.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "bold",
        "tags": ["self-discipline", "strength", "warrior", "character"],
    },
    {
        "content": "Wheresoever you go, go with all your heart.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "romantic",
        "tags": ["wholeheartedness", "passion", "dedication", "heart"],
    },
    {
        "content": "Our greatest glory is not in never falling, but in rising every time we fall.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "motivational",
        "tags": ["resilience", "perseverance", "strength", "growth"],
    },
    {
        "content": "To see what is right and not do it is a lack of courage.",
        "author": "Confucius",
        "category": "Wisdom",
        "mood": "bold",
        "tags": ["courage", "integrity", "morality", "action"],
    },

    # Rumi
    {
        "content": "Let yourself be drawn by the stronger pull of that which you truly love.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "romantic",
        "tags": ["calling", "love", "passion", "intuition"],
    },
    {
        "content": "Do not grieve. Anything you lose comes round in another form.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "reflective",
        "tags": ["healing", "loss", "impermanence", "hope"],
    },
    {
        "content": "You were born with wings, why prefer to crawl through life?",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "motivational",
        "tags": ["potential", "elevation", "freedom", "destiny"],
    },
    {
        "content": "Set your life on fire. Seek those who fan your flames.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "bold",
        "tags": ["passion", "friendship", "courage", "authenticity"],
    },
    {
        "content": "Stop acting so small. You are the universe in ecstatic motion.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "bold",
        "tags": ["cosmos", "greatness", "confidence", "spirit"],
    },
    {
        "content": "Words are a pretext. It is the inner bond that draws one person to another, not words.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "romantic",
        "tags": ["connection", "soul", "understanding", "bond"],
    },
    {
        "content": "The garden of the world has no limits, except in your mind.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["mindset", "abundance", "limitless", "perspective"],
    },
    {
        "content": "When you do things from your soul, you feel a river moving in you, a joy.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "joyful",
        "tags": ["soul", "joy", "purpose", "authenticity"],
    },
    {
        "content": "Sell your cleverness and buy bewilderment.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["humility", "wonder", "mystery", "surrender"],
    },
    {
        "content": "Raise your words, not your voice. It is rain that grows flowers, not thunder.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["gentleness", "speech", "peace", "wisdom"],
    },
    {
        "content": "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.",
        "author": "Rumi",
        "category": "Wisdom",
        "mood": "motivational",
        "tags": ["individuality", "destiny", "courage", "authorship"],
    },

    # Kahlil Gibran
    {
        "content": "Yesterday is but today's memory, and tomorrow is today's dream.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "reflective",
        "tags": ["time", "memory", "dreams", "now"],
    },
    {
        "content": "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "melancholic",
        "tags": ["suffering", "strength", "character", "scars"],
    },
    {
        "content": "Beauty is not in the face; beauty is a light in the heart.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "romantic",
        "tags": ["inner-beauty", "light", "heart", "radiance"],
    },
    {
        "content": "Progress lies not in enhancing what is, but in advancing toward what will be.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["progress", "vision", "evolution", "growth"],
    },
    {
        "content": "To understand the heart and mind of a person, look not at what he has already achieved, but at what he aspires to.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "reflective",
        "tags": ["aspiration", "empathy", "soul", "understanding"],
    },
    {
        "content": "Generosity is giving more than you can, and pride is taking less than you need.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["generosity", "pride", "virtue", "giving"],
    },
    {
        "content": "Trust in dreams, for in them is hidden the gate to eternity.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["dreams", "eternity", "trust", "spirit"],
    },
    {
        "content": "Love gives naught but itself and takes naught but from itself. Love possesses not nor would it be possessed.",
        "author": "Kahlil Gibran",
        "category": "Wisdom",
        "mood": "romantic",
        "tags": ["love", "freedom", "devotion", "purity"],
    },

    # Alan Watts
    {
        "content": "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "joyful",
        "tags": ["change", "flow", "dance", "surrender"],
    },
    {
        "content": "Muddy water is best cleared by leaving it alone.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["calm", "non-action", "clarity", "patience"],
    },
    {
        "content": "You are an aperture through which the universe is looking at and exploring itself.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["cosmos", "consciousness", "unity", "awareness"],
    },
    {
        "content": "This is the real secret of life - to be completely engaged with what you are doing in the here and now.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["presence", "engagement", "now", "mindfulness"],
    },
    {
        "content": "Trying to define yourself is like trying to bite your own teeth.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["identity", "paradox", "zen", "ego"],
    },
    {
        "content": "Man suffers only because he takes seriously what the gods made for fun.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "joyful",
        "tags": ["playfulness", "suffering", "lightness", "humor"],
    },
    {
        "content": "Things are as they are. Looking out into the universe at night, we make no comparisons between right and wrong stars, nor between well and badly arranged constellations.",
        "author": "Alan Watts",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["acceptance", "nature", "non-judgment", "peace"],
    },

    # Sun Tzu & Ancient Thinkers
    {
        "content": "In the midst of chaos, there is also opportunity.",
        "author": "Sun Tzu",
        "category": "Wisdom",
        "mood": "bold",
        "tags": ["strategy", "opportunity", "chaos", "resilience"],
    },
    {
        "content": "The supreme art of war is to subdue the enemy without fighting.",
        "author": "Sun Tzu",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["strategy", "peace", "intelligence", "mastery"],
    },
    {
        "content": "Opportunities multiply as they are seized.",
        "author": "Sun Tzu",
        "category": "Wisdom",
        "mood": "motivational",
        "tags": ["momentum", "action", "opportunity", "initiative"],
    },
    {
        "content": "He will win who knows when to fight and when not to fight.",
        "author": "Sun Tzu",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["discernment", "wisdom", "timing", "patience"],
    },
    {
        "content": "Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness.",
        "author": "Sun Tzu",
        "category": "Wisdom",
        "mood": "philosophical",
        "tags": ["subtlety", "mastery", "quietness", "presence"],
    },
    {
        "content": "Those who follow the Tao are of one with the Tao. Those who follow virtue are of one with virtue.",
        "author": "Zhuangzi",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["unity", "tao", "harmony", "virtue"],
    },
    {
        "content": "Flow with whatever may happen, and let your mind be free. Stay centered by accepting whatever you are doing.",
        "author": "Zhuangzi",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["flow", "freedom", "acceptance", "centering"],
    },
    {
        "content": "Happiness is the absence of the striving for happiness.",
        "author": "Zhuangzi",
        "category": "Wisdom",
        "mood": "serene",
        "tags": ["happiness", "non-striving", "peace", "zen"],
    },
    {
        "content": "The moving finger writes; and, having writ, moves on.",
        "author": "Omar Khayyam",
        "category": "Wisdom",
        "mood": "melancholic",
        "tags": ["time", "destiny", "impermanence", "poetry"],
    },
    {
        "content": "Be happy for this moment. This moment is your life.",
        "author": "Omar Khayyam",
        "category": "Wisdom",
        "mood": "joyful",
        "tags": ["present", "joy", "life", "gratitude"],
    },
]
