# Curated Philosophy Quotes (Stoicism, Classical Greek, Existentialism, Rationalism)

PHILOSOPHY_QUOTES = [
    # Marcus Aurelius
    {
        "content": "You have power over your mind - not outside events. Realize this, and you will find strength.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["stoicism", "mindset", "strength", "inner-peace"],
    },
    {
        "content": "Dwell on the beauty of life. Watch the stars, and see yourself running with them.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["stoicism", "beauty", "cosmos", "perspective"],
    },
    {
        "content": "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "joyful",
        "tags": ["gratitude", "morning", "stoicism", "life"],
    },
    {
        "content": "The best revenge is not to be like that.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["stoicism", "virtue", "character", "integrity"],
    },
    {
        "content": "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["stoicism", "simplicity", "happiness", "mindset"],
    },
    {
        "content": "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["stoicism", "amor-fati", "acceptance", "love"],
    },
    {
        "content": "Never let the future disturb you. You will meet it with the same weapons of reason which today arm you against the present.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["stoicism", "future", "reason", "calm"],
    },
    {
        "content": "If it is not right do not do it; if it is not true do not say it.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["stoicism", "truth", "virtue", "ethics"],
    },
    {
        "content": "The soul becomes dyed with the color of its thoughts.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["stoicism", "thoughts", "soul", "mindfulness"],
    },
    {
        "content": "Confine yourself to the present.",
        "author": "Marcus Aurelius",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["stoicism", "present-moment", "clarity", "peace"],
    },

    # Seneca
    {
        "content": "We suffer more often in imagination than in reality.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["stoicism", "anxiety", "mindset", "fear"],
    },
    {
        "content": "As is a tale, so is life: not how long it is, but how good it is, is what matters.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["stoicism", "life", "meaning", "quality"],
    },
    {
        "content": "Difficulties strengthen the mind, as labor does the body.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "motivational",
        "tags": ["stoicism", "adversity", "growth", "strength"],
    },
    {
        "content": "Begin at once to live, and count each separate day as a separate life.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "motivational",
        "tags": ["stoicism", "living", "today", "urgency"],
    },
    {
        "content": "If one does not know to which port one is sailing, no wind is favorable.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["purpose", "direction", "focus", "wisdom"],
    },
    {
        "content": "True happiness is to enjoy the present, without anxious dependence upon the future.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["stoicism", "happiness", "present", "peace"],
    },
    {
        "content": "He who is brave is free.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["courage", "freedom", "bravery", "stoicism"],
    },
    {
        "content": "All cruelty springs from weakness.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["stoicism", "kindness", "humanity", "insight"],
    },
    {
        "content": "Sometimes even to live is an act of courage.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "melancholic",
        "tags": ["courage", "resilience", "life", "perseverance"],
    },
    {
        "content": "Associate with people who are likely to improve you.",
        "author": "Seneca",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["relationships", "growth", "wisdom", "character"],
    },

    # Epictetus
    {
        "content": "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["gratitude", "contentment", "stoicism", "joy"],
    },
    {
        "content": "We have two ears and one mouth so that we can listen twice as much as we speak.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["listening", "wisdom", "humility", "conversation"],
    },
    {
        "content": "Don't explain your philosophy. Embody it.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["action", "stoicism", "integrity", "example"],
    },
    {
        "content": "Wealth consists not in having great possessions, but in having few wants.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["simplicity", "wealth", "freedom", "stoicism"],
    },
    {
        "content": "It's not what happens to you, but how you react to it that matters.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "motivational",
        "tags": ["perspective", "mindset", "stoicism", "control"],
    },
    {
        "content": "Only the educated are free.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["education", "freedom", "knowledge", "mind"],
    },
    {
        "content": "Circumstances don't make the man, they only reveal him to himself.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["character", "self-awareness", "stoicism", "truth"],
    },
    {
        "content": "No man is free who is not master of himself.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["self-mastery", "discipline", "freedom", "stoicism"],
    },
    {
        "content": "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["freedom", "control", "peace", "stoicism"],
    },
    {
        "content": "Small-minded people blame others. Average people blame themselves. The wise see all blame as foolishness.",
        "author": "Epictetus",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["wisdom", "maturity", "understanding", "peace"],
    },

    # Friedrich Nietzsche
    {
        "content": "He who has a why to live can bear almost any how.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["meaning", "purpose", "resilience", "existentialism"],
    },
    {
        "content": "That which does not kill us makes us stronger.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["strength", "adversity", "resilience", "endurance"],
    },
    {
        "content": "Without music, life would be a mistake.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "joyful",
        "tags": ["music", "art", "life", "passion"],
    },
    {
        "content": "You must have chaos within you to give birth to a dancing star.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["creativity", "passion", "chaos", "transformation"],
    },
    {
        "content": "To live is to suffer, to survive is to find some meaning in the suffering.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "melancholic",
        "tags": ["suffering", "meaning", "survival", "philosophy"],
    },
    {
        "content": "There are no facts, only interpretations.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["truth", "perception", "perspective", "philosophy"],
    },
    {
        "content": "The higher we soar the smaller we appear to those who cannot fly.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["individuality", "elevation", "courage", "greatness"],
    },
    {
        "content": "Whoever fights monsters should see to it that in the process he does not become a monster.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["vigilance", "morality", "soul", "caution"],
    },
    {
        "content": "In individuals, insanity is rare; but in groups, parties, nations and epochs, it is the rule.",
        "author": "Friedrich Nietzsche",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["conformity", "society", "individualism", "thought"],
    },

    # Socrates
    {
        "content": "The unexamined life is not worth living.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["self-examination", "wisdom", "living", "truth"],
    },
    {
        "content": "I know that I am intelligent, because I know that I know nothing.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["humility", "wisdom", "learning", "knowledge"],
    },
    {
        "content": "Wonder is the beginning of wisdom.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["wonder", "curiosity", "wisdom", "discovery"],
    },
    {
        "content": "To find yourself, think for yourself.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["independence", "critical-thinking", "self-discovery", "courage"],
    },
    {
        "content": "The secret of change is to focus all of your energy not on fighting the old, but on building the new.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "motivational",
        "tags": ["change", "focus", "creation", "future"],
    },
    {
        "content": "Be kind, for everyone you meet is fighting a hard battle.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["kindness", "empathy", "compassion", "humanity"],
    },
    {
        "content": "Employ your time in improving yourself by other men's writings so that you shall come easily by what others have labored hard for.",
        "author": "Socrates",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["reading", "learning", "books", "growth"],
    },

    # Plato
    {
        "content": "Courage is knowing what not to fear.",
        "author": "Plato",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["courage", "wisdom", "fear", "clarity"],
    },
    {
        "content": "Wise men speak because they have something to say; fools because they have to say something.",
        "author": "Plato",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["silence", "discernment", "speech", "wisdom"],
    },
    {
        "content": "The measure of a man is what he does with power.",
        "author": "Plato",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["character", "power", "integrity", "leadership"],
    },
    {
        "content": "Ignorance, the root and stem of every evil.",
        "author": "Plato",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["truth", "knowledge", "society", "ethics"],
    },
    {
        "content": "At the touch of love everyone becomes a poet.",
        "author": "Plato",
        "category": "Philosophy",
        "mood": "romantic",
        "tags": ["love", "poetry", "beauty", "soul"],
    },
    {
        "content": "Good actions give strength to ourselves and inspire good actions in others.",
        "author": "Plato",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["virtue", "inspiration", "goodness", "community"],
    },

    # Aristotle
    {
        "content": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "motivational",
        "tags": ["habits", "excellence", "discipline", "character"],
    },
    {
        "content": "Knowing yourself is the beginning of all wisdom.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["self-knowledge", "wisdom", "awareness", "mind"],
    },
    {
        "content": "Educating the mind without educating the heart is no education at all.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["education", "heart", "compassion", "empathy"],
    },
    {
        "content": "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["open-mindedness", "intellect", "discernment", "reason"],
    },
    {
        "content": "Hope is a waking dream.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["hope", "dreams", "optimism", "imagination"],
    },
    {
        "content": "Happiness depends upon ourselves.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["happiness", "agency", "eudaimonia", "life"],
    },
    {
        "content": "Patience is bitter, but its fruit is sweet.",
        "author": "Aristotle",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["patience", "perseverance", "growth", "wisdom"],
    },

    # Albert Camus
    {
        "content": "In the midst of winter, I found there was, within me, an invincible summer.",
        "author": "Albert Camus",
        "category": "Philosophy",
        "mood": "motivational",
        "tags": ["resilience", "inner-strength", "hope", "endurance"],
    },
    {
        "content": "Live to the point of tears.",
        "author": "Albert Camus",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["passion", "intensity", "vulnerability", "life"],
    },
    {
        "content": "Man is the only creature who refuses to be what he is.",
        "author": "Albert Camus",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["human-condition", "identity", "existentialism", "nature"],
    },
    {
        "content": "Real generosity toward the future lies in giving all to the present.",
        "author": "Albert Camus",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["present-moment", "action", "generosity", "future"],
    },
    {
        "content": "Autumn is a second spring when every leaf is a flower.",
        "author": "Albert Camus",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["autumn", "beauty", "seasons", "perspective"],
    },
    {
        "content": "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
        "author": "Albert Camus",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["freedom", "rebellion", "authenticity", "existentialism"],
    },

    # Arthur Schopenhauer & Jean-Paul Sartre & Spinoza
    {
        "content": "Talent hits a target no one else can hit; Genius hits a target no one else can see.",
        "author": "Arthur Schopenhauer",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["genius", "talent", "vision", "creativity"],
    },
    {
        "content": "A man can be himself only so long as he is alone.",
        "author": "Arthur Schopenhauer",
        "category": "Philosophy",
        "mood": "melancholic",
        "tags": ["solitude", "self", "independence", "authenticity"],
    },
    {
        "content": "Every man takes the limits of his own field of vision for the limits of the world.",
        "author": "Arthur Schopenhauer",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["perspective", "limits", "worldview", "understanding"],
    },
    {
        "content": "Freedom is what you do with what's been done to you.",
        "author": "Jean-Paul Sartre",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["freedom", "responsibility", "agency", "existentialism"],
    },
    {
        "content": "We are our choices.",
        "author": "Jean-Paul Sartre",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["choice", "responsibility", "identity", "existentialism"],
    },
    {
        "content": "Commitment is an act, not a word.",
        "author": "Jean-Paul Sartre",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["commitment", "action", "integrity", "purpose"],
    },
    {
        "content": "Peace is not an absence of war, it is a virtue, a state of mind, a disposition for benevolence, confidence, justice.",
        "author": "Baruch Spinoza",
        "category": "Philosophy",
        "mood": "serene",
        "tags": ["peace", "justice", "mindset", "virtue"],
    },
    {
        "content": "I have striven not to laugh at human actions, not to weep at them, nor to hate them, but to understand them.",
        "author": "Baruch Spinoza",
        "category": "Philosophy",
        "mood": "reflective",
        "tags": ["understanding", "compassion", "rationality", "humanity"],
    },
    {
        "content": "Doubt is not a pleasant condition, but certainty is absurd.",
        "author": "Voltaire",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["doubt", "certainty", "wisdom", "humility"],
    },
    {
        "content": "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.",
        "author": "Bertrand Russell",
        "category": "Philosophy",
        "mood": "philosophical",
        "tags": ["intellect", "doubt", "fanaticism", "wisdom"],
    },
    {
        "content": "To conquer fear is the beginning of wisdom.",
        "author": "Bertrand Russell",
        "category": "Philosophy",
        "mood": "bold",
        "tags": ["fear", "courage", "wisdom", "freedom"],
    },
]
